// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuVKDFDyTybEKZELld0mgBAWmq85njlQI',
    appId: '1:966060583440:web:30f4c687c9957283abb895',
    messagingSenderId: '966060583440',
    projectId: 'eppser-1a6a5',
    authDomain: 'eppser-1a6a5.firebaseapp.com',
    storageBucket: 'eppser-1a6a5.appspot.com',
    measurementId: 'G-0B8FHEKFNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzW2ybMDlS4fVxts4SiiuI6WGMvWl-jYs',
    appId: '1:966060583440:android:b82235d7c812d0ecabb895',
    messagingSenderId: '966060583440',
    projectId: 'eppser-1a6a5',
    storageBucket: 'eppser-1a6a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcMr0YhyzlmtAd1Fnt0D0ZWr14RShIdB8',
    appId: '1:966060583440:ios:0a0b833d1b3f20f8abb895',
    messagingSenderId: '966060583440',
    projectId: 'eppser-1a6a5',
    storageBucket: 'eppser-1a6a5.appspot.com',
    androidClientId: '966060583440-6v6qc49d4s1f7596uhhgokafrelthfsp.apps.googleusercontent.com',
    iosBundleId: 'com.eppser.app.eppser',
  );
}
